version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - db-data:/app/data  # Persist SQLite database files

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5001

# Define volumes to persist data
volumes:
  db-data:
